// app/layout.js

import { Syne, Albert_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import HearthMotionProvider from "./components/HearthmotionInitializer/HearthmotionInitializer";
import { ThemeProvider } from "./components/ThemeProvider/ThemeProvider";

// Google Fonts setup
const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-syne",
});

const albertSans = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-albert-sans",
});

export const metadata = {
  title: "GeetBazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${syne.variable} ${albertSans.variable}`}
    >
      <body className="font-syne">
        <ThemeProvider>
          <div id="hm-wrapper">
            <Navbar />
            <div id="hm-content">{children}</div>
          </div>

          <HearthMotionProvider />
        </ThemeProvider>
      </body>
    </html>
  );
}
